import { getProvider } from "@/lib/commerce/registry";
import type { ProviderDescriptor } from "@/lib/commerce/types";

export interface AuthResult { ok: boolean; mode: "live" | "sandbox"; headers?: Record<string, string>; error?: string; refreshed?: boolean; scopes?: string[]; }
export interface AuthTransport { id: string; provider: ProviderDescriptor; detect(): boolean; authenticate(): AuthResult; refresh(): AuthResult; signRequest?(req: { endpoint: string; body?: unknown; headers?: Record<string, string> }): Record<string, string>; }

export const shopifyAuth: AuthTransport = { id:"shopify", provider:getProvider("shopify"), detect(){return Boolean(process.env.SHOPIFY_SHOP&&process.env.SHOPIFY_ADMIN_TOKEN)}, authenticate(){const ok=this.detect();return {ok,mode:ok?"live":"sandbox",headers:ok?{"X-Shopify-Access-Token":process.env.SHOPIFY_ADMIN_TOKEN!}:undefined,error:ok?undefined:"Missing SHOPIFY_ADMIN_TOKEN or SHOPIFY_SHOP"}}, refresh(){return this.authenticate()} };
export const woocommerceAuth: AuthTransport = { id:"woocommerce", provider:getProvider("woocommerce"), detect(){return Boolean(process.env.WOO_STORE_URL&&process.env.WOO_CONSUMER_KEY&&process.env.WOO_CONSUMER_SECRET)}, authenticate(){const ok=this.detect();return {ok,mode:ok?"live":"sandbox",headers:ok?{Authorization:`Basic ${Buffer.from(`${process.env.WOO_CONSUMER_KEY}:${process.env.WOO_CONSUMER_SECRET}`).toString("base64")}`}:undefined,error:ok?undefined:"Missing WOO_CONSUMER_KEY / WOO_CONSUMER_SECRET"}}, refresh(){return this.authenticate()} };
export const squareAuth: AuthTransport = { id:"square", provider:getProvider("square"), detect(){return Boolean(process.env.SQUARE_ACCESS_TOKEN)}, authenticate(){const ok=this.detect();return {ok,mode:ok?"live":"sandbox",headers:ok?{Authorization:`Bearer ${process.env.SQUARE_ACCESS_TOKEN}`,"Square-Version":"2025-01-15","Content-Type":"application/json"}:undefined,error:ok?undefined:"Missing SQUARE_ACCESS_TOKEN"}}, refresh(){return this.authenticate()} };
export const printifyAuth: AuthTransport = { id:"printify", provider:getProvider("printify"), detect(){return Boolean(process.env.PRINTIFY_API_TOKEN)}, authenticate(){const ok=this.detect();return {ok,mode:ok?"live":"sandbox",headers:ok?{Authorization:`Bearer ${process.env.PRINTIFY_API_TOKEN}`}:undefined,error:ok?undefined:"Missing PRINTIFY_API_TOKEN"}}, refresh(){return this.authenticate()} };
export const printfulAuth: AuthTransport = { id:"printful", provider:getProvider("printful"), detect(){return Boolean(process.env.PRINTFUL_API_KEY)}, authenticate(){const ok=this.detect();return {ok,mode:ok?"live":"sandbox",headers:ok?{Authorization:`Bearer ${process.env.PRINTFUL_API_KEY}`}:undefined,error:ok?undefined:"Missing PRINTFUL_API_KEY"}}, refresh(){return this.authenticate()} };
export function getAuthTransport(providerId:string):AuthTransport|null { return ({shopify:shopifyAuth,woocommerce:woocommerceAuth,square:squareAuth,printify:printifyAuth,printful:printfulAuth} as Record<string,AuthTransport>)[providerId]??null; }
export function providerIsAuthenticated(providerId:string):boolean { return getAuthTransport(providerId)?.detect()??false; }
