/** Deterministic procedural artwork generator. No external model required. */

export interface DesignSpec {
  title: string;
  subtitle: string;
  seed: number;
  kind: "design" | "mockup" | "lifestyle";
  style: string;
}

const PALETTES: { name: string; bg: string; ink: string; accent: string; alt: string }[] = [
  { name: "asphalt", bg: "#101418", ink: "#f4f1ea", accent: "#ff5c2b", alt: "#4ea8de" },
  { name: "sunfade", bg: "#1c1a2e", ink: "#ffe8c2", accent: "#ffb703", alt: "#fb8500" },
  { name: "mint", bg: "#0e1f1c", ink: "#eafff4", accent: "#2ec4b6", alt: "#cbf3f0" },
  { name: "blueprint", bg: "#0b2545", ink: "#e6f0ff", accent: "#8ecae6", alt: "#ffffff" },
  { name: "clay", bg: "#241b18", ink: "#fbece0", accent: "#d96c3b", alt: "#8a9b6e" },
  { name: "neon", bg: "#120b1f", ink: "#f2e9ff", accent: "#b14aed", alt: "#30e3ca" },
];
function rng(seed:number){let s=seed%2147483647;if(s<=0)s+=2147483646;return()=>{s=(s*16807)%2147483647;return(s-1)/2147483646;};}
function esc(s:string){return s.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");}
export function paletteFor(seed:number){return PALETTES[seed%PALETTES.length];}
function burst(cx:number,cy:number,r:number,spikes:number,color:string,opacity:number){const pts:string[]=[];for(let i=0;i<spikes*2;i++){const rad=Math.PI*i/spikes;const rr=i%2===0?r:r*.62;pts.push(`${(cx+Math.cos(rad)*rr).toFixed(1)},${(cy+Math.sin(rad)*rr).toFixed(1)}`);}return `<polygon points="${pts.join(" ")}" fill="${color}" opacity="${opacity}" />`;}
function artCore(spec:DesignSpec,w:number,h:number){const p=paletteFor(spec.seed),rand=rng(spec.seed+7),cx=w/2,cy=h/2,words=spec.title.toUpperCase().split(/\s+/).filter(Boolean),line1=words.slice(0,Math.ceil(words.length/2)).join(" "),line2=words.slice(Math.ceil(words.length/2)).join(" ");const rings=Array.from({length:3},(_v,i)=>{const r=h*(.3+i*.07);return `<circle cx="${cx}" cy="${cy}" r="${r.toFixed(1)}" fill="none" stroke="${i%2?p.alt:p.accent}" stroke-width="${(3-i*.7).toFixed(1)}" opacity="${.25+i*.2}" />`;}).join("");const rays=Array.from({length:18},(_v,i)=>{const a=Math.PI*2*i/18,r0=h*.33,r1=h*.46*(.7+rand()*.5);return `<line x1="${(cx+Math.cos(a)*r0).toFixed(1)}" y1="${(cy+Math.sin(a)*r0).toFixed(1)}" x2="${(cx+Math.cos(a)*r1).toFixed(1)}" y2="${(cy+Math.sin(a)*r1).toFixed(1)}" stroke="${p.alt}" stroke-width="2" opacity="0.35" />`;}).join("");const stripes=Array.from({length:5},(_v,i)=>{const y=cy+40+i*9;return `<rect x="${cx-150+i*6}" y="${y}" width="${300-i*12}" height="4" fill="${i%2?p.accent:p.alt}" opacity="0.8" rx="2" />`;}).join("");const size1=Math.min(78,w*.82/Math.max(line1.length,1)*1.65),size2=Math.min(54,w*.7/Math.max(line2.length||1,1)*1.5);return `${burst(cx,cy,h*.42,14,p.accent,.14)}${rings}${rays}<text x="${cx}" y="${cy-14}" text-anchor="middle" font-family="Impact, 'Arial Black', sans-serif" font-size="${size1.toFixed(0)}" fill="${p.ink}" letter-spacing="2">${esc(line1)}</text>${line2?`<text x="${cx}" y="${cy+46}" text-anchor="middle" font-family="Impact, 'Arial Black', sans-serif" font-size="${size2.toFixed(0)}" fill="${p.accent}" letter-spacing="4">${esc(line2)}</text>`:""}${stripes}<text x="${cx}" y="${cy+112}" text-anchor="middle" font-family="Georgia, serif" font-size="18" fill="${p.ink}" opacity="0.75" letter-spacing="6">${esc(spec.subtitle.toUpperCase().slice(0,34))}</text>`;}
export function renderSvg(spec:DesignSpec){const p=paletteFor(spec.seed),w=1000,h=1000;if(spec.kind==="design")return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" width="${w}" height="${h}"><rect width="${w}" height="${h}" fill="${p.bg}" />${artCore(spec,w,h)}<text x="${w/2}" y="${h-36}" text-anchor="middle" font-family="monospace" font-size="16" fill="${p.ink}" opacity="0.35">print-ready · 4500×5400 · 300dpi · ${esc(spec.style)}</text></svg>`;if(spec.kind==="mockup")return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" width="${w}" height="${h}"><defs><linearGradient id="bgm" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#f6f6f4"/><stop offset="100%" stop-color="#dcdcd8"/></linearGradient><clipPath id="print"><rect x="320" y="300" width="360" height="360"/></clipPath></defs><rect width="${w}" height="${h}" fill="url(#bgm)"/><path d="M300 200 L380 160 Q500 230 620 160 L700 200 L760 330 L680 370 L680 850 Q500 880 320 850 L320 370 L240 330 Z" fill="${p.bg}" stroke="#00000022" stroke-width="3"/><g clip-path="url(#print)" transform="translate(320,300) scale(0.36)">${artCore(spec,1000,1000)}</g><text x="${w/2}" y="940" text-anchor="middle" font-family="system-ui, sans-serif" font-size="22" fill="#6b6b6b">AGENT MOCKUP · front placement · ${esc(spec.style)}</text></svg>`;return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" width="${w}" height="${h}"><defs><radialGradient id="lg" cx="50%" cy="30%"><stop offset="0%" stop-color="${p.alt}" stop-opacity="0.45"/><stop offset="100%" stop-color="${p.bg}"/></radialGradient></defs><rect width="${w}" height="${h}" fill="url(#lg)"/><g transform="translate(150,150) scale(0.7)" opacity="0.95">${artCore(spec,1000,1000)}</g><rect x="0" y="${h-120}" width="${w}" height="120" fill="#00000055"/><text x="${w/2}" y="${h-50}" text-anchor="middle" font-family="system-ui, sans-serif" font-size="30" fill="#ffffff">${esc(spec.title)}</text></svg>`;}
